name: schedule - ejecucion diaria

on:
  schedule:
    - cron: '0 13 * * *'

jobs:
  run-tests-prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: instalar las dependencias
        run: npm ci

      - name: correr los tests de cypress
        run: npx cypress run --e2e --browser chrome
